title: On the Identification and Evaluation of Bad Smell Agglomerations
description: This page functions as an online appendix for the project "On the Identification and Evaluation of Bad Smell
Agglomerations" by Amanda Santana, Daniel Cruz and Eduardo Figueiredo.
theme: jekyll-theme-leap-day
