title: On the Identification and Evaluation of Bad Smell Agglomerations
description: This page is as an online appendix for the project "On the Identification and Evaluation of Bad Smell Agglomerations"
theme: jekyll-theme-leap-day
